In [2]:
!pip install librosa


In [15]:
import librosa
import librosa.display
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import Audio


In [10]:
import pandas as pd

download_path = '../vocal_patterns/data'
metadata_file = f"{download_path}/dataset_tags.csv"

df = pd.read_csv(metadata_file)
df.head()


path exercise technique  \
0  /Users/elsagregoire/code/ElsaGregoire/vocal_pa...    Other   vibrato   
1  /Users/elsagregoire/code/ElsaGregoire/vocal_pa...    Other   vibrato   
2  /Users/elsagregoire/code/ElsaGregoire/vocal_pa...    Other   vibrato   
3  /Users/elsagregoire/code/ElsaGregoire/vocal_pa...    Other  straight   
4  /Users/elsagregoire/code/ElsaGregoire/vocal_pa...    Other  straight   

               filename  
0    m6_row_vibrato.wav  
1   m6_caro_vibrato.wav  
2   m6_dona_vibrato.wav  
3  m6_caro_straight.wav  
4   m6_row_straight.wav

In [4]:
audio_path = '/Users/elsagregoire/Desktop/Vocal Set Le Wagon/arpeggios/arpeggios f1/slow_forte/f1_arpeggios_c_slow_forte_a.wav'


### Load the audio file

In [11]:
y, sr = librosa.load(audio_path)


In [12]:
y #y is the data as numpy array
# which gives us the amplitude of the wave form at a certain moment


array([1.3526442e-04, 1.4985875e-04, 9.8155477e-05, ..., 4.6974109e-04,
       4.5185169e-04, 4.9337966e-04], dtype=float32)

In [13]:
y.shape  # 165853 / 22050 = 7,52 seconds long


(165853,)

In [14]:
sr # sr is the smpling rate


22050

In [16]:
Audio(data=y, rate=sr)


### Waveplot

### truncating the wav file 

In [18]:
start_sample = int(0.0 * sr)
end_sample = int(6.0 * sr)
truncated_signal = y[start_sample:end_sample]
len(truncated_signal)


In [20]:
Audio(data=truncated_signal, rate=sr)


### Padding if too long (here tryout with 10 sec)

In [21]:
current_length = len(y)
current_length


165853

In [22]:
padding_both_sides = int((10.0 * sr - current_length) / 2)
padding_both_sides


27323

In [23]:
padded_signal = librosa.util.pad_center(y, size= (current_length + padding_both_sides * 2))
padded_signal


array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [24]:
len(padded_signal)


220499

### Pitch shift

In [26]:
steps = float(3)
y_pitched_up=librosa.effects.pitch_shift(y, sr=sr, n_steps=steps)
Audio(data=y_pitched_up, rate=sr)


In [27]:
y_pitched_down = librosa.effects.pitch_shift(y, sr=sr, n_steps=-2)
Audio(data=y_pitched_down, rate=sr)


### Time stretch

In [28]:
faster_rate = 1.5
y_stretched_faster = librosa.effects.time_stretch(y, rate=faster_rate)
Audio(data=y_stretched_faster, rate=sr)


In [29]:
slower_rate = 0.5
y_stretched_slower = librosa.effects.time_stretch(y, rate=slower_rate)
Audio(data=y_stretched_slower, rate=sr)


### Add noise

In [30]:
noise_level = 0.005
np.random.normal(size=len(y))


array([ 0.67566496,  1.01690541,  0.75686887, ...,  1.47569057,
       -0.16541856, -1.20692627])

In [31]:
y_noisy = y + (noise_level * np.random.normal(size=len(y)))
Audio(data=y_noisy, rate=sr)


### mel spectrogram